# ===============================
# Application Name
# ===============================
spring.application.name=quantity-measurement-app
server.port=8081

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/quantitymeasurementdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false   

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# Swagger / SpringDoc OpenAPI
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.paths-to-match=/**
springdoc.swagger-ui.title=Quantity Measurement API
springdoc.swagger-ui.path=/swagger-ui.html

app.jwt.secret=mysupersecurejwtsecretkeymysupersecurejwtsecretkey123
app.jwt.expiration=3600000
# GOOGLE LOGIN
spring.security.oauth2.client.registration.google.client-id=test-client-id

spring.security.oauth2.client.registration.google.client-secret=test-client-secret
spring.security.oauth2.client.registration.google.scope=email,profile 